[project]
name = "enderleaf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "albumentations>=2.0.8",
    "black>=26.3.1",
    "flet[all]>=0.86.0",
    "ipympl>=0.10.0",
    "ipywidgets>=8.1.8",
    "ipywidgets-bokeh>=1.7.0",
    "joblib>=1.5.3",
    "jupyter-bokeh>=4.0.5",
    "jupyterlab>=4.5.6",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pandas>=3.0.2",
    "panel>=1.8.10",
    "plotly>=6.7.0",
    "pretty>=0.1",
    "pyserial>=3.5",
    "qreader>=3.16",
    "rich>=14.3.3",
    "scikit-image>=0.26.0",
    "seaborn>=0.13.2",
    "websockets>=16.1",
]
